<a href="https://colab.research.google.com/github/noctxrne/ICT_Notes/blob/main/NumPy_%26_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NumPys**


Fast numerical computations on arrays/matrices

## **Problems**

In [ ]:
import numpy as np
x=np.array([12,12,23,45,105])
x

array([ 12,  12,  23,  45, 105])

In [ ]:
type(x)

numpy.ndarray

In [ ]:
#Method
x.shape

(5,)

In [ ]:
#To find dimension of array
x.ndim

1

In [ ]:
#To find the datatype of element in array
x.dtype

dtype('int64')

In [ ]:
#Creating a 2 dimensional array
y=np.array([[1,2,3],
            [3,4,5]])
y

array([[1, 2, 3],
       [3, 4, 5]])

In [ ]:
y.shape

(2, 3)

In [ ]:
y.dtype

dtype('int64')

In [ ]:
xy=np.array([1.2,3.4,5.6,7.8],dtype=np.int64)
xy

array([1, 3, 5, 7])

In [ ]:
#zeros
A1=np.zeros((3,4),dtype=np.int64)
A1


array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
#ones
A2=np.ones((3,4))
A2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
#Identity Matrix
A2=np.eye((3),dtype=np.float64)
A2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#diagonal matrix
A10=np.diag([100,200,300,50])
A10

array([[100,   0,   0,   0],
       [  0, 200,   0,   0],
       [  0,   0, 300,   0],
       [  0,   0,   0,  50]])

In [ ]:
#arange
a3=np.arange(10,50,4) #(startvalue, stopvalue,step)
a3

array([10, 14, 18, 22, 26, 30, 34, 38, 42, 46])

In [ ]:
#reshape
a4=np.reshape(a3,(5,2))
a4

array([[10, 14],
       [18, 22],
       [26, 30],
       [34, 38],
       [42, 46]])

In [ ]:
#Random float matrix with custom order the (value wouldbe between 0 and 1)
a5=np.random.random((4,5))
a5

array([[0.12548493, 0.94086782, 0.09913355, 0.04657407, 0.26645488],
       [0.68551145, 0.23241908, 0.32165365, 0.46162222, 0.99226517],
       [0.44943103, 0.14600505, 0.47574194, 0.65601295, 0.58392424],
       [0.4502457 , 0.48719893, 0.86320141, 0.71404602, 0.03898285]])

In [ ]:
#Random integer matrix with custom order and range
a6=np.random.randint(10,100,size=(5,5))
a6

array([[90, 50, 13, 43, 23],
       [90, 30, 40, 83, 95],
       [78, 36, 71, 48, 90],
       [44, 59, 98, 21, 98],
       [50, 40, 93, 72, 73]])

In [ ]:
#print a specific row
a6[0]

array([63, 45, 96, 27, 10])

In [ ]:
a6[-1]

array([17, 19, 14, 74, 67])

In [ ]:
#print till nth row
a6[:2]

array([[65, 69, 62, 79, 27],
       [16, 85, 94, 80, 40]])

In [ ]:
#print specific part of a matrix
a6[1:4,2:5]

array([[40, 83, 95],
       [71, 48, 90],
       [98, 21, 98]])

### **`NumPy Useful Fuctions:`**

In [ ]:
#2x3 array filled with 7
np.full((2,3), 7)

array([[7, 7, 7],
       [7, 7, 7]])

In [ ]:
#printing sum of elements of each rows separately
a6.sum(axis=1)

array([219, 338, 323, 320, 328])

In [ ]:
#printing sum of elements of each columns separately
a7=a6.sum(axis=0)
a7

array([205, 268, 228, 291, 245])

In [ ]:
#mean
np.mean(a7)

np.float64(247.4)

In [ ]:
#median
np.median(a6)


np.float64(25.301573073625285)

In [ ]:
#Standard Deviation
np.std(a6)

In [ ]:
#variance
np.var(a6)

np.float64(640.1696000000001)

In [ ]:
#minimum and maximum
print(f"Minimum: {np.min(a6)}")
print(f"Maximum: {np.max(a6)}")

Minimum: 12
Maximum: 88


In [ ]:
#Percentile

np.percentile(data, 50) #median
np.percentile(data, 25) #q1
np.percentile(data, 75) #q3

In [ ]:
#
x=np.random.randint(0,100,size=(1,10))
y=np.random.randint(0,100,size=(1,10))
np.corrcoef(x,y)

array([[ 1.        , -0.12301575],
       [-0.12301575,  1.        ]])

In [ ]:
#Array Split

a8=np.random.randint(0,10,size=(4,5))
a8

array([[5, 3, 3, 1, 1],
       [4, 8, 6, 2, 3],
       [7, 0, 7, 3, 4],
       [8, 8, 2, 7, 0]])

In [ ]:
np.split(a8,2)

[array([[5, 3, 3, 1, 1],
        [4, 8, 6, 2, 3]]),
 array([[7, 0, 7, 3, 4],
        [8, 8, 2, 7, 0]])]

# **Pandas**

Used for Data manipulation and analysis

## **Problems**

In [ ]:
import pandas as pd

In [ ]:
#Creating a list
s=pd.Series([1,2,3,4,5,np.nan,6,7])
s

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
5    NaN
6    6.0
7    7.0
dtype: float64

In [ ]:
#Creating a Data frame by converting a 5x3 random array
df=pd.DataFrame(np.random.randint(0,100,size=(5,3)),columns=['A','B','C'])
df


A   B   C
0  28  61  62
1  92  88   4
2  64  11  56
3   5  49  74
4  14  56  71

In [ ]:
#Creating a dataframe of Calories and duration
data={
    'calories':[100,200,300,400,500,600,700],
    'duration':[10,20,30,40,50,60,70]
}
calDf=pd.DataFrame(data,index=['sunday','monday','tuesday','wednesday','thursday','friday','saturday'])
calDf

calories  duration
sunday          100        10
monday          200        20
tuesday         300        30
wednesday       400        40
thursday        500        50
friday          600        60
saturday        700        70

In [ ]:
calDf.calories

sunday       100
monday       200
tuesday      300
wednesday    400
thursday     500
friday       600
saturday     700
Name: calories, dtype: int64

In [ ]:
calDf.duration

sunday       10
monday       20
tuesday      30
wednesday    40
thursday     50
friday       60
saturday     70
Name: duration, dtype: int64

In [ ]:
calDf.reset_index(drop=True)

calories  duration
0       100        10
1       200        20
2       300        30
3       400        40
4       500        50
5       600        60
6       700        70

In [ ]:
calDf.reset_index(drop=False)

index  calories  duration
0     sunday       100        10
1     monday       200        20
2    tuesday       300        30
3  wednesday       400        40
4   thursday       500        50
5     friday       600        60
6   saturday       700        70

In [ ]:
url="https://docs.google.com/spreadsheets/d/1VdgNwORHh4HlimuuEgrsixRgko2Gi1YdnlUYAnkPFR8/export?format=csv&gid=0"
calDf=pd.read_csv(url)
calDf

Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

In [ ]:
calDf=pd.read_csv('/content/data - Sheet1.csv')
calDf

Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

In [ ]:
calDf.head()

Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0

In [ ]:
calDf.tail()

Duration  Pulse  Maxpulse  Calories
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

In [ ]:
calDf.head(2)

Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0

In [ ]:
calDf.tail(2)

Duration  Pulse  Maxpulse  Calories
167        75    120       150     320.4
168        75    125       150     330.4

In [ ]:
calDf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Duration  169 non-null    int64  
 1   Pulse     169 non-null    int64  
 2   Maxpulse  169 non-null    int64  
 3   Calories  164 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 5.4 KB


In [ ]:
calDf.size

676

In [ ]:
calDf.describe()

Duration       Pulse    Maxpulse     Calories
count  169.000000  169.000000  169.000000   164.000000
mean    63.846154  107.461538  134.047337   375.790244
std     42.299949   14.510259   16.450434   266.379919
min     15.000000   80.000000  100.000000    50.300000
25%     45.000000  100.000000  124.000000   250.925000
50%     60.000000  105.000000  131.000000   318.600000
75%     60.000000  111.000000  141.000000   387.600000
max    300.000000  159.000000  184.000000  1860.400000

In [ ]:
calDf.isna()

Duration  Pulse  Maxpulse  Calories
0       False  False     False     False
1       False  False     False     False
2       False  False     False     False
3       False  False     False     False
4       False  False     False     False
..        ...    ...       ...       ...
164     False  False     False     False
165     False  False     False     False
166     False  False     False     False
167     False  False     False     False
168     False  False     False     False

[169 rows x 4 columns]

In [ ]:
calDf.isna().sum()

Duration    0
Pulse       0
Maxpulse    0
Calories    5
dtype: int64

In [ ]:
calDf[calDf['Calories']<=100]

Duration  Pulse  Maxpulse  Calories
89         20     83       107      50.3
93         15     80       100      50.5
100        20     95       112      77.7
104        30     92       108      92.7
107        30     90       120      86.2

In [ ]:
calDf[calDf['Calories']<=100 & calDf['Duration']]

Empty DataFrame
Columns: [Duration, Pulse, Maxpulse, Calories]
Index: []

In [ ]:
calDf.drop(['Calories'],axis=1)

Duration  Pulse  Maxpulse
0          60    110       130
1          60    117       145
2          60    103       135
3          45    109       175
4          45    117       148
..        ...    ...       ...
164        60    105       140
165        60    110       145
166        60    115       145
167        75    120       150
168        75    125       150

[169 rows x 3 columns]

In [ ]:
calDf.nunique() #number of unique items

Duration     16
Pulse        47
Maxpulse     57
Calories    142
dtype: int64

In [ ]:
calDf['Duration'].unique()

array([ 60,  45,  30,  80,  20, 210, 160, 180, 150, 300,  90, 120, 270,
        15,  25,  75])

In [ ]:
calDf['Duration'].value_counts()

Duration
60     79
45     35
30     16
20      9
90      8
150     4
180     3
120     3
75      2
160     2
210     2
15      2
80      1
300     1
270     1
25      1
Name: count, dtype: int64

In [ ]:
calDf.groupby('Duration')['Calories'].mean()

Duration
15       87.350000
20      151.600000
25      244.200000
30      192.125000
45      273.236364
60      339.675000
75      325.400000
80      643.100000
90      541.800000
120     666.833333
150     939.400000
160     943.700000
180     733.600000
210    1618.200000
270    1729.000000
300    1500.200000
Name: Calories, dtype: float64

In [ ]:
calDf['Calories_per_min']=calDf['Calories']/calDf['Duration']
calDf

Duration  Pulse  Maxpulse  Calories  Calories_per_min
0          60    110       130     409.1          6.818333
1          60    117       145     479.0          7.983333
2          60    103       135     340.0          5.666667
3          45    109       175     282.4          6.275556
4          45    117       148     406.0          9.022222
..        ...    ...       ...       ...               ...
164        60    105       140     290.8          4.846667
165        60    110       145     300.0          5.000000
166        60    115       145     310.2          5.170000
167        75    120       150     320.4          4.272000
168        75    125       150     330.4          4.405333

[169 rows x 5 columns]